<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ClientController;


// Redirect root to dashboard or login
Route::get('/', function () {
    return redirect()->route('dashboard');
});

// All protected routes (must be logged in)
Route::middleware(['auth'])->group(function () {

    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    // Clients
    Route::resource('clients', ClientController::class);

    // Admin only routes
    Route::middleware(['admin'])->group(function () {
        Route::get('/settings', function () {
            return view('settings.index');
        })->name('settings.index');
    });

});

// Auth routes (login, register, logout etc - generated by Breeze)
require __DIR__.'/auth.php';